apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crown-fashion-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crown-fashion
  template:
    metadata:
      labels:
        app: crown-fashion
    spec:
      containers:
      - name: crown-fashion-container
        image: crown-fashion:0.1.0
---
apiVersion: v1
kind: Service
metadata:
  name: crown-fashion-service
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: crown-fashion
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: crown-fashion-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: crown-fashion.localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: crown-fashion-service
          servicePort: http